In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [3]:
# Creating tensors with tf.constants
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Number of dimension
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [8]:
matrix = tf.constant([[10,7],
                    [7,10]])

In [9]:
matrix.ndim

2

In [10]:
matrx2 = tf.constant([[10.,8.],
                     [8.,4,],
                     [3.,1.]], dtype = tf.float16)

In [11]:
matrx2.ndim

2

In [14]:
# Creating a 3d tensor

tensor =  tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [20]:
changeable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changeable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [21]:
# Trying to change a changable tensor 

changeable_tensor[0] =2

TypeError: 'ResourceVariable' object does not support item assignment

In [22]:
changeable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 7])>

In [26]:
#Creatnig random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1.normal(shape = (2,3,1))

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702],
        [ 0.07595026]],

       [[-1.2573844 ],
        [-0.23193763],
        [-1.8107855 ]]], dtype=float32)>

In [27]:
# Shuffling the tensors

unshuffled_tensor = tf.constant([[2,1],
                                [4,2],
                                [9,5]])

In [28]:
unshuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [4, 2],
       [9, 5]])>

In [29]:
# random.shuffle shuffles the tensor along the first dimension
tf.random.shuffle(unshuffled_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 2],
       [2, 1],
       [9, 5]])>

In [34]:
# Converting a numpy array into tensorflow tensor
# Difference between the both is that a tensor can be run on a GPU which is much faster for computing

import numpy as np 

np_array = np.arange(1,25,1, dtype = np.int32)

In [35]:
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [36]:
converted_array = tf.constant(np_array, shape = (2,3,4))

In [37]:
converted_array

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [2]:
# Rank 4 tensor

rank_4_tensor = tf.zeros(shape = (2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [6]:
# Rank 2 tensor

rank_2_tensor = tf.constant([[3,4],
                            [5,9]])
rank_2_tensor

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [7]:
# Get the last item of each row of the tensor 
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 9])>

In [8]:
# Tensor Manipulation

tensor = tf.constant([[9,3],
                     [8,4]])
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 13],
       [18, 14]])>

In [9]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[90, 30],
       [80, 40]])>

In [10]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1, -7],
       [-2, -6]])>

In [11]:
# Using functions
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[90, 30],
       [80, 40]])>

In [12]:
# Multiplying matrces
tf.matmul(tensor, rank_2_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 63],
       [44, 68]])>

In [13]:
tf.matmul(tensor, rank_4_tensor)

InvalidArgumentError: cannot compute BatchMatMulV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:BatchMatMulV2]

In [14]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [27]:
# Multiplying matrices after reshaping
reshaped_product = tf.matmul(tf.reshape(X,shape = (2,3)),Y)
reshaped_product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [23]:
reshaped_matrix = tf.reshape(X,shape = (2,3))
reshaped_matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [22]:
X, tf.transpose(X), tf.reshape(X, shape = (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [25]:
# Multplying matrices after transposing
transposed_product = tf.matmul(tf.transpose(X),Y )
transposed_product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [28]:
# Transposed and reshaped product are not the same
transposed_product, reshaped_product

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]])>)