In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [3]:
# Creating tensors with tf.constants
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Number of dimension
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [8]:
matrix = tf.constant([[10,7],
                    [7,10]])

In [9]:
matrix.ndim

2

In [10]:
matrx2 = tf.constant([[10.,8.],
                     [8.,4,],
                     [3.,1.]], dtype = tf.float16)

In [11]:
matrx2.ndim

2

In [14]:
# Creating a 3d tensor

tensor =  tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [20]:
changeable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changeable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [21]:
# Trying to change a changable tensor 

changeable_tensor[0] =2

TypeError: 'ResourceVariable' object does not support item assignment

In [22]:
changeable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 7])>

In [26]:
#Creatnig random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1.normal(shape = (2,3,1))

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702],
        [ 0.07595026]],

       [[-1.2573844 ],
        [-0.23193763],
        [-1.8107855 ]]], dtype=float32)>

In [27]:
# Shuffling the tensors

unshuffled_tensor = tf.constant([[2,1],
                                [4,2],
                                [9,5]])

In [28]:
unshuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [4, 2],
       [9, 5]])>

In [29]:
# random.shuffle shuffles the tensor along the first dimension
tf.random.shuffle(unshuffled_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 2],
       [2, 1],
       [9, 5]])>

In [34]:
# Converting a numpy array into tensorflow tensor
# Difference between the both is that a tensor can be run on a GPU which is much faster for computing

import numpy as np 

np_array = np.arange(1,25,1, dtype = np.int32)

In [35]:
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [36]:
converted_array = tf.constant(np_array, shape = (2,3,4))

In [37]:
converted_array

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [2]:
# Rank 4 tensor

rank_4_tensor = tf.zeros(shape = (2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [6]:
# Rank 2 tensor

rank_2_tensor = tf.constant([[3,4],
                            [5,9]])
rank_2_tensor

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [7]:
# Get the last item of each row of the tensor 
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 9])>

In [8]:
# Tensor Manipulation

tensor = tf.constant([[9,3],
                     [8,4]])
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 13],
       [18, 14]])>

In [9]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[90, 30],
       [80, 40]])>

In [10]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1, -7],
       [-2, -6]])>

In [11]:
# Using functions
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[90, 30],
       [80, 40]])>

In [12]:
# Multiplying matrces
tf.matmul(tensor, rank_2_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 63],
       [44, 68]])>

In [13]:
tf.matmul(tensor, rank_4_tensor)

InvalidArgumentError: cannot compute BatchMatMulV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:BatchMatMulV2]

In [14]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [27]:
# Multiplying matrices after reshaping
reshaped_product = tf.matmul(tf.reshape(X,shape = (2,3)),Y)
reshaped_product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [23]:
reshaped_matrix = tf.reshape(X,shape = (2,3))
reshaped_matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [22]:
X, tf.transpose(X), tf.reshape(X, shape = (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [25]:
# Multplying matrices after transposing
transposed_product = tf.matmul(tf.transpose(X),Y )
transposed_product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [28]:
# Transposed and reshaped product are not the same
transposed_product, reshaped_product

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]])>)

In [3]:
# Changing the data type of tensors
a = tf.constant([[2.,5.],
                [3,7]])
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 5.],
       [3., 7.]], dtype=float32)>

In [4]:
# Change the data type from float 32 to float 16
# 32bit precision

a = tf.cast(a,dtype = tf.float16)
a.dtype

tf.float16

In [5]:
# Tensor Aggregation
# Getting the absolute value of a tensor

a = tf.constant([-3,-6])
tf.abs(a)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6])>

In [7]:
import numpy as np
random_tensor = tf.constant(np.random.randint(0,100,size = 50))
random_tensor

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([83, 33, 57, 86, 32, 29, 74, 62, 67, 82, 59, 93, 94, 24, 59, 17, 72,
       73, 89, 82, 29, 14, 49, 56, 63, 10, 85,  3, 44, 16, 25, 21, 95, 64,
       26, 95, 40, 81, 28, 18, 82, 66, 89, 81, 45,  7, 14, 53, 21, 50])>

In [8]:
tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [9]:
tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=95>

In [10]:
tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=52>

In [11]:
tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2637>

In [16]:
random_tensor = tf.cast(random_tensor, dtype = tf.float32)
tf.math.reduce_variance(random_tensor, 0)

<tf.Tensor: shape=(), dtype=float32, numpy=784.47235>

In [17]:
tf.math.reduce_std(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=28.008434>

In [20]:
tf.random.set_seed(33)
tensor = tf.random.uniform(shape = [50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.33143902, 0.21867776, 0.0160141 , 0.2876439 , 0.79751086,
       0.21710753, 0.6433041 , 0.36862898, 0.50054467, 0.71634173,
       0.42660952, 0.53803957, 0.22099257, 0.81026185, 0.57730436,
       0.85869336, 0.3830887 , 0.10151541, 0.40971458, 0.53684866,
       0.675125  , 0.8787942 , 0.2530595 , 0.5888306 , 0.8912947 ,
       0.8457856 , 0.3994583 , 0.24162519, 0.581491  , 0.74078023,
       0.7363901 , 0.96084607, 0.713277  , 0.6095383 , 0.2995093 ,
       0.5917554 , 0.891641  , 0.24231768, 0.38349473, 0.9355582 ,
       0.33619452, 0.6970371 , 0.41257358, 0.51162803, 0.5456264 ,
       0.5786649 , 0.37017047, 0.28624272, 0.07297945, 0.32062662],
      dtype=float32)>

In [21]:
# Find the positional maximum of a tensor i.e the index at which the maximum number resides
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=31>

In [22]:
tensor[31]

<tf.Tensor: shape=(), dtype=float32, numpy=0.96084607>

In [23]:
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [24]:
tensor[2]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0160141>

In [25]:
# Squeezing a tensor = Removing all one dim axes
tf.random.set_seed(44)
b = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
b

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.21691406, 0.7038727 , 0.28590095, 0.47886062, 0.97233224,
           0.10853219, 0.14845335, 0.48970163, 0.20112908, 0.11934876,
           0.88207614, 0.7417917 , 0.84117174, 0.88684595, 0.11674249,
           0.3902886 , 0.23854637, 0.31396985, 0.82154906, 0.2543156 ,
           0.50986934, 0.26460743, 0.07325482, 0.5148798 , 0.4464289 ,
           0.71551406, 0.23824298, 0.55751514, 0.14421296, 0.85819876,
           0.27457988, 0.07887137, 0.67671466, 0.9421835 , 0.9284011 ,
           0.75563824, 0.25915694, 0.999091  , 0.9562758 , 0.9998728 ,
           0.5068165 , 0.08749485, 0.54555345, 0.17844772, 0.340019  ,
           0.09060669, 0.6250659 , 0.4788208 , 0.7997385 , 0.9735943 ]]]]],
      dtype=float32)>

In [28]:
b_squeezed = tf.squeeze(b)
b_squeezed, b_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.21691406, 0.7038727 , 0.28590095, 0.47886062, 0.97233224,
        0.10853219, 0.14845335, 0.48970163, 0.20112908, 0.11934876,
        0.88207614, 0.7417917 , 0.84117174, 0.88684595, 0.11674249,
        0.3902886 , 0.23854637, 0.31396985, 0.82154906, 0.2543156 ,
        0.50986934, 0.26460743, 0.07325482, 0.5148798 , 0.4464289 ,
        0.71551406, 0.23824298, 0.55751514, 0.14421296, 0.85819876,
        0.27457988, 0.07887137, 0.67671466, 0.9421835 , 0.9284011 ,
        0.75563824, 0.25915694, 0.999091  , 0.9562758 , 0.9998728 ,
        0.5068165 , 0.08749485, 0.54555345, 0.17844772, 0.340019  ,
        0.09060669, 0.6250659 , 0.4788208 , 0.7997385 , 0.9735943 ],
       dtype=float32)>,
 TensorShape([50]))

In [29]:
# One hot encoding a list 

list_1 = [1,2,3,4,6,7]
tf.one_hot(list_1, depth = 6) # Depth specifies the shape and size of the tensor

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Exercise
* Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
* Find the shape, rank and size of the tensors you created in 1.
* Create two tensors containing random values between 0 and 1 with shape [5, 300].
* Multiply the two tensors you created in 3 using matrix multiplication.
* Multiply the two tensors you created in 3 using dot product.
* Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
* Find the min and max values of the tensor you created in 6 along the first axis.
* Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
* Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
* One-hot encode the tensor you created in 9.

In [7]:
scalar = tf.constant(2)
scalar.shape, scalar.ndim


(TensorShape([]), 0)

In [5]:
vector = tf.constant([4,3])
vector.shape, vector.ndim

(TensorShape([2]), 1)

In [6]:
matrix = tf.constant([[4,6],
                     [5,2]])
matrix.shape, matrix.ndim

(TensorShape([2, 2]), 2)

In [ ]:
import numpy as np
random_tensor = tf.constant()